[features]
seeds = false
skip-lint = false
[programs.devnet]
splitwave = "pP24ZPhQLvSSri8hB5DdoUxRGRLCiYxdf5MH1s93dfd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
